### ISSUE TITLE
diff_meth_pos is broken : TypeError: rv_generic.interval() missing 1 required positional argument: 'confidence'

### ISSUE THREAD

**Issue by gldlv** [FoxoTech/methylize#30]
Putting it here for the record. When trying to use diff_meth_pos, the following error can happen, seemingly in joblib : 

` ` ` 
TypeError: rv_generic.interval() missing 1 required positional argument: 'confidence'
` ` ` 

Other things may or may not pop in the traceback depending on whether you launch the command from a jupyter notebook

**_To fix it: downgrade scipy to 1.10 :_** 

` ` ` 
pip install --force-reinstall -v "scipy==1.10"
` ` `

**Comment by luiscruvinel** [comment]
I patched locally by substituting 'alpha' for 'confidence' in the call of the student_t.interval function
